# Generated by Django 6.0 on 2025-12-30 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Website Name')),
                ('website', models.URLField(default='', verbose_name='Website Url')),
                ('date_opened', models.DateField(auto_now_add=True)),
                ('letitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('restaurent_type', models.CharField(choices=[('PK', 'Pakistani'), ('IT', 'Italian'), ('IN', 'Indian'), ('JP', 'Japanese'), ('KR', 'Korean')], default='PK', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('2.5', 'Two Five'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')], default='2.5', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='rating.restaurent')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('restaurent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='rating.restaurent')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('restaurents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.restaurent')),
                ('staffname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='restaurents',
            field=models.ManyToManyField(related_name='staff', through='rating.StaffSalary', to='rating.restaurent'),
        ),
    ]
